#! /bin/sh
### BEGIN INIT INFO
# Provides:          alarm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Alarm Service
# Description:       This file starts and stops the alarm service
### END INIT INFO

# Author: Tony @ oddwires.co.uk

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Oddwires Alarm Service"
NAME=alarm
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="--options args"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
        echo "Starting $DESC"
        sudo /var/www/Scripts/alarm.sh &;;
  stop)
        echo "Stopping $DESC"
        sudo killall alarm.sh ;;
  *)
       echo "Usage: $SCRIPTNAME {start|stop}"
       exit 3 ;;
esac

:
